name: Evitar push diretamente em main e develop
on: [push]
jobs:
  valid-repo-main:
    if: github.repository == 'main'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  valid-repo-develop:
    needs: valid-repo-main
    if: github.repository == 'develop'
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  run-tests:
    needs: [valid-repo-main, valid-repo-develop]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Setup  Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm install
          yarn install

      - run: |
          npx jest
