name: Execução de testes
on:
  push:
    branches:
      - main
      - develop
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v3

      - name: Setup  Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm ci
          rm -rf node_modules && yarn install --frozen-lockfile

      - run: |
          npx jest --ci
